# Generated by Django 6.0.5 on 2026-05-26 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_artist_alter_video_show_show_artist'),
    ]

    operations = [
        # Recréer la FK Video->Show avec ON UPDATE CASCADE ON DELETE RESTRICT
        migrations.RunSQL(
            sql="""
                ALTER TABLE reservations_video
                DROP FOREIGN KEY reservations_video_show_id_aac8310d_fk_reservations_show_id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reservations_video
                ADD CONSTRAINT reservations_video_show_id_aac8310d_fk_reservations_show_id
                FOREIGN KEY (show_id) REFERENCES reservations_show(id)
                ON UPDATE CASCADE ON DELETE RESTRICT;
            """,
            reverse_sql="""
                ALTER TABLE reservations_video
                DROP FOREIGN KEY reservations_video_show_id_aac8310d_fk_reservations_show_id;
            """,
        ),
        # Recréer la FK Show->Artist avec ON UPDATE CASCADE ON DELETE RESTRICT
        migrations.RunSQL(
            sql="""
                ALTER TABLE reservations_show
                DROP FOREIGN KEY reservations_show_artist_id_0205f2cd_fk_reservations_artist_id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reservations_show
                ADD CONSTRAINT reservations_show_artist_id_0205f2cd_fk_reservations_artist_id
                FOREIGN KEY (artist_id) REFERENCES reservations_artist(id)
                ON UPDATE CASCADE ON DELETE RESTRICT;
            """,
            reverse_sql="""
                ALTER TABLE reservations_show
                DROP FOREIGN KEY reservations_show_artist_id_0205f2cd_fk_reservations_artist_id;
            """,
        ),
    ]
